services:
  build_linux:
    build: docker/build_linux
    volumes:
    - "..:/repo"
  build_web:
    build: docker/build_web
    volumes:
    - "..:/repo"
  build_android:
    build: docker/build_android
    volumes:
    - "..:/repo"